### ISSUE TITLE
Docker-compose beacon fails to start

### ISSUE THREAD

**Issue by blankdots** [EGA-archive/beacon-2.x#74] opened 2021-08-10 07:18 UTC
### Expected Behavior

beacon is available at `localhost:5050`

### Current Behavior

the beacon errors in container with these logs
```
Attaching to idp, idp-db, beacon-permissions, beacon, beacon-db
beacon         | [beacon.utils.db][ INFO ] (L36) Creating a connection pool to beacon-db:5432
beacon         | [beacon.utils.db][DEBUG ] (L57) Ping successful
beacon         | [beacon.utils.db][DEBUG ] (L80) ----------- acquiring connection
beacon         | [beacon.utils.db][ INFO ] (L116) Retrieving last modified date
beacon         | [beacon.utils.db][DEBUG ] (L119) QUERY: SELECT MAX(updated_at) FROM public.dataset;
beacon         | [beacon.utils.db][DEBUG ] (L92) ----------- releasing connection
beacon         | Traceback (most recent call last):
beacon         |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
beacon         |     return _run_code(code, main_globals, None,
beacon         |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
beacon         |     exec(code, run_globals)
beacon         |   File "/beacon/beacon/__main__.py", line 107, in <module>
beacon         |     main()
beacon         |   File "/beacon/beacon/__main__.py", line 95, in main
beacon         |     web.run_app(beacon,
beacon         |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web.py", line 508, in run_app
beacon         |     loop.run_until_complete(main_task)
beacon         |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
beacon         |     return future.result()
beacon         |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web.py", line 319, in _run_app
beacon         |     await runner.setup()
beacon         |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_runner.py", line 275, in setup
beacon         |     self._server = await self._make_server()
beacon         |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_runner.py", line 375, in _make_server
beacon         |     await self._app.startup()
beacon         |   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 416, in startup
beacon         |     await self.on_startup.send(self)
beacon         |   File "/usr/local/lib/python3.8/site-packages/aiohttp/signals.py", line 34, in send
beacon         |     await receiver(*args, **kwargs)  # type: ignore
beacon         |   File "/beacon/beacon/__main__.py", line 24, in initialize
beacon         |     update_datetime = (await db.get_last_modified_date()).strftime(conf.datetime_format)
beacon         | AttributeError: 'NoneType' object has no attribute 'strftime'
```

`db.get_last_modified_date()` seems to return `None`

### Possible Solution

Tackle the `None` return from database and if there is no update time, default to start time

### Steps to Reproduce

Followed the steps at: https://github.com/EGA-archive/beacon-2.x/tree/master/deploy

1. `git clone`, `cd beacon`, `git lfs install`
2. `docker-compose build beacon`
3. `docker-compose up -d db` - the db is empty
4. `docker-compose up -d`
5. see error that  the beacon is not available

### Context (Environment)

We are trying to use beacon 2.x in beacon network to set it up and do queries to it.

**Comment by blankdots** [comment] 2021-08-10 07:34
looking a tad deeper in the db logs it seems that `git lfs` did not work as intended ?
```
beacon-db      | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/2.sql.gz
beacon-db      | gunzip: invalid magic
```

**Comment by silverdaz** [comment] 2021-08-30 11:18
The None is caused by an empty database, and it should be handled as you mentioned. Good catch.

The empty database is caused by a failing test data loading, which in turn comes from a failing `git lfs`.

Fixing the docker-compose script wouldn't change that. Moreover, the docker-compose script is just a toy and not a bullet-proof startup script. If we receive a None value from the database, for something that _should_ return a value, I prefer to fail early and bail out with a descriptive message. We should _not_ handle the case and hide the error. This exludes the `restart: always` on purpose. That's a different approach to programming (debatable, of course), where you let it fail and handle the error _outside_ the current code.

In any case, we received an email from Github stating
```Git LFS has been disabled on the organization EGA-archive because you’ve exceeded your data plan```
and asking us to
```purchase additional data packs to cover your bandwidth and storage usage```

As far as I know there is no plan to do that, and we should probably find another way to share the demo data.
This is the reason why you get an empty database and you get a None value for some database fields.

~~I'm leaving the issue open, in case we want to brainstorm here about the solution.~~
~~If we do it somewhere, we can close that issue and re-open another one.~~

I'm closing the issue, and you can open a new one to have a discussion on the above limitation.

**Closed by silverdaz** 2021-08-30 11:18 UTC

**Comment by blankdots** [comment] 2021-08-30 16:34
ok.
> I prefer to fail early and bail out with a descriptive message.

which issue can i track for that ?
